
package com.ninamadeira;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerPort", targetNamespace = "http://ninamadeira.com.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerPort {


    /**
     * 
     * @param getAllCustomerDetailRequest
     * @return
     *     returns com.ninamadeira.GetAllCustomerDetailResponse
     */
    @WebMethod(operationName = "GetAllCustomerDetail")
    @WebResult(name = "GetAllCustomerDetailResponse", targetNamespace = "http://ninamadeira.com.br", partName = "GetAllCustomerDetailResponse")
    public GetAllCustomerDetailResponse getAllCustomerDetail(
        @WebParam(name = "GetAllCustomerDetailRequest", targetNamespace = "http://ninamadeira.com.br", partName = "GetAllCustomerDetailRequest")
        GetAllCustomerDetailRequest getAllCustomerDetailRequest);

    /**
     * 
     * @param insertCustomerRequest
     * @return
     *     returns com.ninamadeira.InsertCustomerResponse
     */
    @WebMethod(operationName = "InsertCustomer")
    @WebResult(name = "InsertCustomerResponse", targetNamespace = "http://ninamadeira.com.br", partName = "InsertCustomerResponse")
    public InsertCustomerResponse insertCustomer(
        @WebParam(name = "InsertCustomerRequest", targetNamespace = "http://ninamadeira.com.br", partName = "InsertCustomerRequest")
        InsertCustomerRequest insertCustomerRequest);

    /**
     * 
     * @param deleteCustomerRequest
     * @return
     *     returns com.ninamadeira.DeleteCustomerResponse
     */
    @WebMethod(operationName = "DeleteCustomer")
    @WebResult(name = "DeleteCustomerResponse", targetNamespace = "http://ninamadeira.com.br", partName = "DeleteCustomerResponse")
    public DeleteCustomerResponse deleteCustomer(
        @WebParam(name = "DeleteCustomerRequest", targetNamespace = "http://ninamadeira.com.br", partName = "DeleteCustomerRequest")
        DeleteCustomerRequest deleteCustomerRequest);

    /**
     * 
     * @param getCustomerDetailRequest
     * @return
     *     returns com.ninamadeira.GetCustomerDetailResponse
     */
    @WebMethod(operationName = "GetCustomerDetail")
    @WebResult(name = "GetCustomerDetailResponse", targetNamespace = "http://ninamadeira.com.br", partName = "GetCustomerDetailResponse")
    public GetCustomerDetailResponse getCustomerDetail(
        @WebParam(name = "GetCustomerDetailRequest", targetNamespace = "http://ninamadeira.com.br", partName = "GetCustomerDetailRequest")
        GetCustomerDetailRequest getCustomerDetailRequest);

}
